version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: learnitDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LearnIt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: learnit
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

volumes:
  postgres_data: